import Navbar from '@/components/Navbar'
import './globals.css'
import Footer from '@/components/Footer'

export const metadata = {
  title: 'Donut Spot',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='max-w-screen-xl	m-auto'>
        <Navbar />
        {children}
        <Footer />
        </div>
        
        </body>
    </html>
  )
}
