import Navbar from '@/components/Navbar'
import './globals.css'
import Footer from '@/components/Footer'
import Provider from '@/SessionProvider'


export const metadata = {
  title: 'Donut Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Provider>
      <div className='container'>
       <Navbar />
        {children}
        <Footer />
       </div>
      </Provider>
        </body>
    </html>
  )
}
